services:
  app:
    build:
      context: .               
    container_name: js-scss-dev
    working_dir: /app
    volumes:
      - .:/app                 
      - /app/node_modules      
    tty: true
    stdin_open: true
